# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/timlzh/Documents/DLNA/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 625)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.device_table = QtWidgets.QTableWidget(self.centralwidget)
        self.device_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.device_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.device_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.device_table.setObjectName("device_table")
        self.device_table.setColumnCount(3)
        self.device_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.device_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.device_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.device_table.setHorizontalHeaderItem(2, item)
        self.device_table.horizontalHeader().setCascadingSectionResizes(False)
        self.device_table.horizontalHeader().setDefaultSectionSize(250)
        self.gridLayout.addWidget(self.device_table, 2, 0, 1, 3)
        self.resolution_combo = QtWidgets.QComboBox(self.centralwidget)
        self.resolution_combo.setObjectName("resolution_combo")
        self.resolution_combo.addItem("")
        self.resolution_combo.addItem("")
        self.resolution_combo.addItem("")
        self.resolution_combo.addItem("")
        self.resolution_combo.addItem("")
        self.gridLayout.addWidget(self.resolution_combo, 1, 1, 1, 2)
        self.host_ip_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.host_ip_edit.setObjectName("host_ip_edit")
        self.gridLayout.addWidget(self.host_ip_edit, 0, 1, 1, 2)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout.addWidget(self.stop_button, 3, 2, 1, 1)
        self.scan_device_button = QtWidgets.QPushButton(self.centralwidget)
        self.scan_device_button.setObjectName("scan_device_button")
        self.gridLayout.addWidget(self.scan_device_button, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DLNA Screen Caster"))
        self.label.setText(_translate("MainWindow", "Host IP"))
        self.label_2.setText(_translate("MainWindow", "Cast Resolution"))
        item = self.device_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Device"))
        item = self.device_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Location"))
        item = self.device_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Manufacturer"))
        self.resolution_combo.setItemText(0, _translate("MainWindow", "1920*1080 [16:9]"))
        self.resolution_combo.setItemText(1, _translate("MainWindow", "1920*1200 [16:10]"))
        self.resolution_combo.setItemText(2, _translate("MainWindow", "2560*1440 [16:9]"))
        self.resolution_combo.setItemText(3, _translate("MainWindow", "2560*1600 [16:10]"))
        self.resolution_combo.setItemText(4, _translate("MainWindow", "1280x720 [16:9]"))
        self.stop_button.setText(_translate("MainWindow", "Stop Casting"))
        self.scan_device_button.setText(_translate("MainWindow", "Scan Device"))
